config/routes.rb
Rails.application.routes.draw do
  mount Payola::Engine => '/payola', as: :payola
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  get '/home', to: 'dashboard#home'

  namespace :api do
    post '/check', to: 'status#check'

    get '/', to: 'docs#index'
    get '/search', to: 'search#index'
    get '/bower-search', to: 'bower_search#index'
    get '/searchcode', to: 'projects#searchcode'

    get '/subscriptions', to: 'subscriptions#index'
    get '/subscription/:platform/:name', to: 'subscriptions#show'
    post '/subscription/:platform/:name', to: 'subscriptions#create'
    put '/subscription/:platform/:name', to: 'subscriptions#update'
    delete '/subscription/:platform/:name', to: 'subscriptions#destroy'

    get '/github/issues/help-wanted', to: 'github_issues#help_wanted'
    get '/github/issues/first-pull-request', to: 'github_issues#first_pull_request'

    get '/github/search', to: 'github_repositories#search'

    get '/github/:login/repositories', to: 'github_users#repositories'
    get '/github/:login/projects', to: 'github_users#projects'

    get '/github/:owner/:name/dependencies', to: 'github_repositories#dependencies', constraints: { :name => /[^\/]+/ }
    get '/github/:owner/:name/projects', to: 'github_repositories#projects', constraints: { :name => /[^\/]+/ }
    get '/github/:owner/:name', to: 'github_repositories#show', constraints: { :name => /[^\/]+/ }

    get '/github/:login', to: 'github_users#show'

    get '/:platform/:name/:version/tree', to: 'tree#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\-\%]+/, :version => /[\w\.\-]+/ }, as: :version_tree
    get '/:platform/:name/:version/dependencies', to: 'projects#dependencies', constraints: { :platform => /[\w\-]+/, :name => /[\w\-\%]+/, :version => /[\w\.\-]+/ }
    get '/:platform/:name/dependent_repositories', to: 'projects#dependent_repositories', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
    get '/:platform/:name/dependents', to: 'projects#dependents', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
    get '/:platform/:name/tree', to: 'tree#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }, as: :tree
    get '/:platform/:name', to: 'projects#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
  end

  namespace :admin do
    resources :projects do
      collection do
        get 'deprecated'
        get 'unmaintained'
      end
    end
    resources :project_suggestions
    resources :github_repositories do
      member do
        put 'deprecate'
        put 'unmaintain'
      end
      collection do
        get 'deprecated'
        get 'unmaintained'
      end
    end
    get '/stats', to: 'stats#index', as: :stats
    get '/stats/github', to: 'stats#github', as: :github_stats
  end

  get '/trending', to: 'projects#trending', as: :trending_projects
  get '/explore', to: 'explore#index'
  get '/collections', to: 'collections#index', as: :collections
  get '/explore/:language-:keyword-libraries', to: 'collections#show', as: :collection

  get '/github/issues', to: 'github_issues#index', as: :issues
  get '/github/issues/your-dependencies', to: 'github_issues#your_dependencies', as: :your_dependencies_issues

  get '/pricing', to: 'account_subscriptions#plans', as: :pricing
  resources :account_subscriptions

  get '/recommendations', to: 'recommendations#index', as: :recommendations

  post '/hooks/github', to: 'hooks#github'

  get '/repositories', to: 'dashboard#index', as: :repositories
  get '/dashboard', to: redirect("/repositories")
  get '/muted', to: 'dashboard#muted', as: :muted
  post '/repositories/sync', to: 'dashboard#sync', as: :sync
  post '/watch/:github_repository_id', to: 'dashboard#watch', as: :watch
  post '/unwatch/:github_repository_id', to: 'dashboard#unwatch', as: :unwatch

  resource :account do
    member do
      get 'delete'
      put 'disable_emails'
    end
  end

  root to: 'projects#index'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  resources :licenses, constraints: { :id => /.*/ }, :defaults => { :format => 'html' }
  resources :languages
  resources :keywords, constraints: { :id => /.*/ }, :defaults => { :format => 'html' }
  resources :subscriptions
  resources :repository_subscriptions
  get '/subscribe/:project_id', to: 'subscriptions#subscribe', as: :subscribe

  get '/stats', to: redirect('/admin/stats')

  get 'bus-factor', to: 'projects#bus_factor', as: :bus_factor
  get '/unlicensed-libraries', to: 'projects#unlicensed', as: :unlicensed
  get 'unmaintained-libraries', to: 'projects#unmaintained', as: :unmaintained
  get 'deprecated-libraries', to: 'projects#deprecated', as: :deprecated
  get 'removed-libraries', to: 'projects#removed', as: :removed

  get '/help-wanted', to: 'github_issues#help_wanted', as: :help_wanted
  get '/first-pull-request', to: 'github_issues#first_pull_request', as: :first_pull_request

  get '/platforms', to: 'platforms#index', as: :platforms

  get '/github/languages', to: 'github_repositories#languages', as: :github_languages
  get '/github/search', to: 'github_repositories#search', as: :github_search
  get '/github/trending', to: 'github_repositories#hacker_news', as: :trending
  get '/github/new', to: 'github_repositories#new', as: :new_repos

  get '/github/organisations', to: 'github_organisations#index', as: :github_organisations
  get '/github/timeline', to: 'github_repositories#timeline', as: :github_timeline

  get '/github/:login/issues', to: 'users#issues'
  get '/github/:login/dependency-issues', to: 'users#dependency_issues'
  get '/github/:login/repositories', to: 'users#repositories', as: :user_repositories
  get '/github/:login/contributions', to: 'users#contributions', as: :user_contributions
  get '/github/:login/projects', to: 'users#projects', as: :user_projects
  get '/github/:login/contributors', to: 'users#contributors', as: :user_contributors
  get '/github/:login', to: 'users#show', as: :user

  get '/search', to: 'search#index'

  get '/sitemap.xml.gz', to: redirect("https://#{ENV['FOG_DIRECTORY']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz")

  get '/enable_private', to: 'sessions#enable_private', as: :enable_private
  get '/enable_public', to: 'sessions#enable_public', as: :enable_public
  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  post '/auth/failure',             to: 'sessions#failure'


  get '/github/:owner/:name', to: 'github_repositories#show', as: :github_repository, :defaults => { :format => 'html' }, constraints: { :name => /[\w\.\-\%]+/ }
  get '/github/:owner/:name/contributors', to: 'github_repositories#contributors', as: :github_repository_contributors, format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/sourcerank', to: 'github_repositories#sourcerank', as: :github_repository_sourcerank, format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/forks', to: 'github_repositories#forks', as: :github_repository_forks, format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/tags', to: 'github_repositories#tags', as: :github_repository_tags, format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/dependency-issues', to: 'github_repositories#dependency_issues', format: false, constraints: { :name => /[^\/]+/ }

  get '/github/:owner/:name/web_hooks', to: 'web_hooks#index', as: :github_repository_web_hooks, format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/web_hooks/new', to: 'web_hooks#new', as: :new_github_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
  delete '/github/:owner/:name/web_hooks/:id', to: 'web_hooks#destroy', as: :github_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
  patch '/github/:owner/:name/web_hooks/:id', to: 'web_hooks#update', format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/web_hooks/:id/edit', to: 'web_hooks#edit', as: :edit_github_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
  post '/github/:owner/:name/web_hooks/:id/test', to: 'web_hooks#test', as: :test_github_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
  post '/github/:owner/:name/web_hooks', to: 'web_hooks#create', format: false, constraints: { :name => /[^\/]+/ }

  get '/github', to: 'github_repositories#index', as: :github

  get '/about', to: 'pages#about', as: :about

  if Rails.env.development?
    get '/rails/mailers'         => "rails/mailers#index"
    get '/rails/mailers/*path'   => "rails/mailers#preview"
  end

  get '/:platform/:name/suggestions', to: 'project_suggestions#new', as: :project_suggestions, constraints: { :name => /.*/ }
  post '/:platform/:name/suggestions', to: 'project_suggestions#create', constraints: { :name => /.*/ }

  # project routes
  get '/:platform/:name/unsubscribe', to: 'projects#unsubscribe', constraints: { :name => /.*/ }, as: :unsubscribe_project
  get '/:platform/:name/usage', to: 'project_usage#show', as: :project_usage, constraints: { :name => /.*/ }, :defaults => { :format => 'html' }
  post '/:platform/:name/mute', to: 'projects#mute', as: :mute_project, constraints: { :name => /.*/ }
  delete '/:platform/:name/unmute', to: 'projects#unmute', as: :unmute_project, constraints: { :name => /.*/ }
  get '/:platform/:name/tree', to: 'tree#show', constraints: { :name => /[\w\.\-\%]+/ }, as: :tree
  get '/:platform/:name/sourcerank', to: 'projects#sourcerank', as: :project_sourcerank, constraints: { :name => /.*/ }

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  def index
    @platforms = Project.popular_platforms
  end

  def show
    find_platform
    scope = Project.platform(@platform_name).maintained
    @created = scope.few_versions.order('projects.created_at DESC').limit(5).includes(:github_repository)
    @updated = scope.many_versions.order('projects.latest_release_published_at DESC').limit(5).includes(:github_repository)
    @watched = scope.most_watched.limit(5).includes(:github_repository)
    @dependend = scope.most_dependents.limit(5).includes(:github_repository)
    @popular = scope.order('projects.rank DESC').limit(5).includes(:github_repository)
    @trending = scope.includes(:github_repository).recently_created.hacker_news.limit(5)
    @dependent_repos = scope.most_dependent_repos.limit(5).includes(:github_repository)

    @color = @platform.color

    facets = Project.facets(filters: {platform: @platform_name}, :facet_limit => 10)

    @languages = facets[:languages][:terms]
    @licenses = facets[:licenses][:terms].reject{ |t| t.term.downcase == 'other' }
    @keywords = facets[:keywords][:terms]
  end
end

app/views/platforms/_list_platform.html.erb
<p class='list'>
  <strong><%= link_to platform_name(platform.term), search_path(platforms: platform.term, languages: @language, licenses: @license.try(:id), keywords: @keyword) %></strong>
  <small><%= pluralize number_to_human(platform['count']), 'project' %></small>
</p>

app/views/platforms/_platform.html.erb
<div class='platform col-xs-6 col-sm-4 col-md-4'>
  <h4>
    <div class="pictogram pictogram-<%= platform.term.downcase %>"></div>
    <div class="blurb">
      <%= link_to platform_name(platform.term), platform_path(platform.term.downcase) %>
      <small><%= number_to_human platform['count'] %> Projects</small>
    </div>
  </h4>
</div>

app/views/platforms/index.html.erb
<% title "Platforms - Libraries.io" %>
<% description "All the open source platforms that projects have been published to" %>
<h1>
  <%= fa_icon 'archive' %>
  Package Managers
</h1><hr>
<div class='row'>
  <div class="col-md-8">
    <div class="row">
      <%= render partial: 'platform', collection: @platforms %>
    </div>
  </div>
  <div class="col-md-4">
    <%= render 'adsense/sidebar' %>
  </div>
</div>

app/views/platforms/show.html.erb
<% title "#{platform_name(@platform_name)} - Libraries.io" %>
<% description "A detailed listing of the most popular, recently updated and most watched #{platform_name(@platform_name)} projects online" %>
<% content_for :atom, auto_discovery_link_tag(:atom, search_url(platforms: @platform_name, sort: 'latest_release_published_at', order: 'desc', format: :atom), title: "Updated #{platform_name(@platform_name)} Projects") %>
<% content_for :atom, auto_discovery_link_tag(:atom, search_url(platforms: @platform_name, sort: 'created_at', order: 'desc', format: :atom), title: "New #{platform_name(@platform_name)} Projects") %>

<% cache([@platform_name, 'platforms:show', 'v1'], :expires_in => 1.hour) do %>
<div class='row'>
  <div class='col-sm-6'>
    <h1>
      <div class="pictogram pictogram-lg pictogram-<%= @platform_name.downcase %>"></div>
      <%= platform_name(@platform_name) %>
    </h1>
  </div>
  <div class="col-sm-6">
    <br>
    <p>
      Website: <%= link_to @platform::URL, @platform::URL %>
    </p>
    <p>
      Total Packages: <%= number_with_delimiter Project.platform(@platform_name).not_removed.count %>
    </p>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-8">
    <div class="row">
      <% if @trending.any? %>
        <div class='col-sm-6 platform-column'>
          <h4>
            Trending <%= platform_name(@platform_name) %> Projects
            <small class='more'>
              <%= link_to 'See more &raquo;'.html_safe, trending_projects_path(platforms: @platform_name) %>
            </small>
          </h4>
          <%= render @trending, cache: true %>
        </div>
      <% end %>

      <% if @popular.any? %>
        <div class='col-sm-6 platform-column'>
          <h4>
            Popular <%= platform_name(@platform_name) %> Projects
            <small class='more'>
              <%= link_to 'See more &raquo;'.html_safe, search_path(platforms: @platform_name, sort: 'rank', order: 'desc') %>
            </small>
          </h4>
          <%= render @popular, cache: true %>
        </div>
      <% end %>

      <% if @dependent_repos.any? %>
        <div class='col-sm-6 platform-column'>
          <h4>Most Used <%= platform_name(@platform_name) %> Projects</h4>
          <%= render @dependent_repos, cache: true %>
        </div>
      <% end %>

      <% if @dependend.any? %>
        <div class='col-sm-6 platform-column'>
          <h4>Most Depended upon <%= platform_name(@platform_name) %> Projects</h4>
          <%= render @dependend, cache: true %>
        </div>
      <% end %>

      <% if @updated.any? %>
      <div class='col-sm-6 platform-column'>
        <h4>
          <%= link_to search_url(platforms: @platform_name, sort: 'latest_release_published_at', order: 'desc', format: :atom), class: 'rss' do %>
            <%= fa_icon "rss-square" %>
          <% end %>
          Updated <%= platform_name(@platform_name) %> Projects
          <small class='more'>
            <%= link_to 'See more &raquo;'.html_safe, search_path(platforms: @platform_name, sort: 'latest_release_published_at', order: 'desc') %>
          </small>
        </h4>
        <%= render @updated, cache: true %>
      </div>
      <% end %>
      <% if @created.any? %>
        <div class='col-sm-6 platform-column'>
          <h4>
            <%= link_to search_url(platforms: @platform_name, sort: 'created_at', order: 'desc', format: :atom), class: 'rss' do %>
              <%= fa_icon "rss-square" %>
            <% end %>
            New <%= platform_name(@platform_name) %> Projects
            <small class='more'>
              <%= link_to 'See more &raquo;'.html_safe, search_path(platforms: @platform_name, sort: 'created_at', order: 'desc') %>
            </small>
          </h4>
          <%= render @created, cache: true %>
        </div>
      <% end %>

      <% if @watched.any? %>
          <div class='col-sm-6 platform-column'>
            <h4>Most Watched <%= platform_name(@platform_name) %> Projects</h4>
            <%= render @watched, cache: true %>
          </div>
          <div class="col-sm-6">
            <%= render 'adsense/sidebar' %>
          </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4">
    <%= render 'adsense/sidebar' %>
    <div class='row'>
      <% if @languages.many? %>
        <div class='col-md-12 col-sm-4'>
          <h4>
            <%= fa_icon 'code' %>
            Top <%= platform_name(@platform_name) %> Languages
          </h4>
          <%= render partial: 'languages/list_language', collection: @languages, as: :language %>
        </div>
      <% end %>
      <% if @licenses.many? %>
        <div class='col-md-12 col-sm-4'>
          <h4>
            <%= fa_icon 'gavel' %>
            Top <%= platform_name(@platform_name) %> Licenses
          </h4>
          <%= render partial: 'licenses/list_license', collection: @licenses, as: :license %>
        </div>
      <% end %>
      <% if @keywords.many? %>
        <div class='col-md-12 col-sm-4'>
          <h4>
            <%= fa_icon 'tags' %>
            Top <%= platform_name(@platform_name) %> Keywords
          </h4>
          <%= render partial: 'keywords/list_keyword', collection: @keywords, as: :keyword %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>