config/routes.rb
Rails.application.routes.draw do
  mount Payola::Engine => '/payola', as: :payola
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  get '/home', to: 'dashboard#home'

  namespace :api do
    post '/check', to: 'status#check'

    get '/', to: 'docs#index'
    get '/search', to: 'search#index'
    get '/bower-search', to: 'bower_search#index'
    get '/searchcode', to: 'projects#searchcode'

    get '/subscriptions', to: 'subscriptions#index'
    get '/subscription/:platform/:name', to: 'subscriptions#show'
    post '/subscription/:platform/:name', to: 'subscriptions#create'
    put '/subscription/:platform/:name', to: 'subscriptions#update'
    delete '/subscription/:platform/:name', to: 'subscriptions#destroy'

    get '/github/issues/help-wanted', to: 'github_issues#help_wanted'
    get '/github/issues/first-pull-request', to: 'github_issues#first_pull_request'

    get '/github/search', to: 'github_repositories#search'

    get '/github/:login/repositories', to: 'github_users#repositories'
    get '/github/:login/projects', to: 'github_users#projects'

    get '/github/:owner/:name/dependencies', to: 'github_repositories#dependencies', constraints: { :name => /[^\/]+/ }
    get '/github/:owner/:name/projects', to: 'github_repositories#projects', constraints: { :name => /[^\/]+/ }
    get '/github/:owner/:name', to: 'github_repositories#show', constraints: { :name => /[^\/]+/ }

    get '/github/:login', to: 'github_users#show'

    get '/:platform/:name/:version/tree', to: 'tree#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\-\%]+/, :version => /[\w\.\-]+/ }, as: :version_tree
    get '/:platform/:name/:version/dependencies', to: 'projects#dependencies', constraints: { :platform => /[\w\-]+/, :name => /[\w\-\%]+/, :version => /[\w\.\-]+/ }
    get '/:platform/:name/dependent_repositories', to: 'projects#dependent_repositories', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
    get '/:platform/:name/dependents', to: 'projects#dependents', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
    get '/:platform/:name/tree', to: 'tree#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }, as: :tree
    get '/:platform/:name', to: 'projects#show', constraints: { :platform => /[\w\-]+/, :name => /[\w\.\-\%]+/ }
  end

  namespace :admin do
    resources :projects do
      collection do
        get 'deprecated'
        get 'unmaintained'
      end
    end
    resources :project_suggestions
    resources :github_repositories do
      member do
        put 'deprecate'
        put 'unmaintain'
      end
      collection do
        get 'deprecated'
        get 'unmaintained'
      end
    end
    get '/stats', to: 'stats#index', as: :stats
    get '/stats/github', to: 'stats#github', as: :github_stats
  end

  get '/trending', to: 'projects#trending', as: :trending_projects
  get '/explore', to: 'explore#index'
  get '/collections', to: 'collections#index', as: :collections
  get '/explore/:language-:keyword-libraries', to: 'collections#show', as: :collection

  get '/github/issues', to: 'github_issues#index', as: :issues
  get '/github/issues/your-dependencies', to: 'github_issues#your_dependencies', as: :your_dependencies_issues

  get '/pricing', to: 'account_subscriptions#plans', as: :pricing
  resources :account_subscriptions

  get '/recommendations', to: 'recommendations#index', as: :recommendations

  post '/hooks/github', to: 'hooks#github'

  get '/repositories', to: 'dashboard#index', as: :repositories
  get '/dashboard', to: redirect("/repositories")
  get '/muted', to: 'dashboard#muted', as: :muted
  post '/repositories/sync', to: 'dashboard#sync', as: :sync
  post '/watch/:github_repository_id', to: 'dashboard#watch', as: :watch
  post '/unwatch/:github_repository_id', to: 'dashboard#unwatch', as: :unwatch

  resource :account do
    member do
      get 'delete'
      put 'disable_emails'
    end
  end

  root to: 'projects#index'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  resources :licenses, constraints: { :id => /.*/ }, :defaults => { :format => 'html' }
  resources :languages
  resources :keywords, constraints: { :id => /.*/ }, :defaults => { :format => 'html' }
  resources :subscriptions
  resources :repository_subscriptions
  get '/subscribe/:project_id', to: 'subscriptions#subscribe', as: :subscribe

  get '/stats', to: redirect('/admin/stats')

  get 'bus-factor', to: 'projects#bus_factor', as: :bus_factor
  get '/unlicensed-libraries', to: 'projects#unlicensed', as: :unlicensed
  get 'unmaintained-libraries', to: 'projects#unmaintained', as: :unmaintained
  get 'deprecated-libraries', to: 'projects#deprecated', as: :deprecated
  get 'removed-libraries', to: 'projects#removed', as: :removed

  get '/help-wanted', to: 'github_issues#help_wanted', as: :help_wanted
  get '/first-pull-request', to: 'github_issues#first_pull_request', as: :first_pull_request

  get '/platforms', to: 'platforms#index', as: :platforms

  get '/github/languages', to: 'github_repositories#languages', as: :github_languages
  get '/github/search', to: 'github_repositories#search', as: :github_search
  get '/github/trending', to: 'github_repositories#hacker_news', as: :trending
  get '/github/new', to: 'github_repositories#new', as: :new_repos

  get '/github/organisations', to: 'github_organisations#index', as: :github_organisations
  get '/github/timeline', to: 'github_repositories#timeline', as: :github_timeline

  get '/github/:login/issues', to: 'users#issues'
  get '/github/:login/dependency-issues', to: 'users#dependency_issues'
  get '/github/:login/repositories', to: 'users#repositories', as: :user_repositories
  get '/github/:login/contributions', to: 'users#contributions', as: :user_contributions
  get '/github/:login/projects', to: 'users#projects', as: :user_projects
  get '/github/:login/contributors', to: 'users#contributors', as: :user_contributors
  get '/github/:login', to: 'users#show', as: :user

  get '/search', to: 'search#index'

  get '/sitemap.xml.gz', to: redirect("https://#{ENV['FOG_DIRECTORY']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz")

  get '/enable_private', to: 'sessions#enable_private', as: :enable_private
  get '/enable_public', to: 'sessions#enable_public', as: :enable_public
  get '/login',  to: 'sessions#new',     as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  post '/auth/failure',             to: 'sessions#failure'


  get '/github/:owner/:name', to: 'github_repositories#show', as: :github_repository, :defaults => { :format => 'html' }, constraints: { :name => /[\w\.\-\%]+/ }
  get '/github/:owner/:name/contributors', to: 'github_repositories#contributors', as: :github_repository_contributors, format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/sourcerank', to: 'github_repositories#sourcerank', as: :github_repository_sourcerank, format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/forks', to: 'github_repositories#forks', as: :github_repository_forks, format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/tags', to: 'github_repositories#tags', as: :github_repository_tags, format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/dependency-issues', to: 'github_repositories#dependency_issues', format: false, constraints: { :name => /[^\/]+/ }

  get '/github/:owner/:name/web_hooks', to: 'web_hooks#index', as: :github_repository_web_hooks, format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/web_hooks/new', to: 'web_hooks#new', as: :new_github_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
  delete '/github/:owner/:name/web_hooks/:id', to: 'web_hooks#destroy', as: :github_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
  patch '/github/:owner/:name/web_hooks/:id', to: 'web_hooks#update', format: false, constraints: { :name => /[^\/]+/ }
  get '/github/:owner/:name/web_hooks/:id/edit', to: 'web_hooks#edit', as: :edit_github_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
  post '/github/:owner/:name/web_hooks/:id/test', to: 'web_hooks#test', as: :test_github_repository_web_hook, format: false, constraints: { :name => /[^\/]+/ }
  post '/github/:owner/:name/web_hooks', to: 'web_hooks#create', format: false, constraints: { :name => /[^\/]+/ }

  get '/github', to: 'github_repositories#index', as: :github

  get '/about', to: 'pages#about', as: :about

  if Rails.env.development?
    get '/rails/mailers'         => "rails/mailers#index"
    get '/rails/mailers/*path'   => "rails/mailers#preview"
  end

  get '/:platform/:name/suggestions', to: 'project_suggestions#new', as: :project_suggestions, constraints: { :name => /.*/ }
  post '/:platform/:name/suggestions', to: 'project_suggestions#create', constraints: { :name => /.*/ }

  # project routes
  get '/:platform/:name/unsubscribe', to: 'projects#unsubscribe', constraints: { :name => /.*/ }, as: :unsubscribe_project
  get '/:platform/:name/usage', to: 'project_usage#show', as: :project_usage, constraints: { :name => /.*/ }, :defaults => { :format => 'html' }
  post '/:platform/:name/mute', to: 'projects#mute', as: :mute_project, constraints: { :name => /.*/ }
  delete '/:platform/:name/unmute', to: 'projects#unmute', as: :unmute_project, constraints: { :name => /.*/ }
  get '/:platform/:name/tree', to: 'tree#show', constraints: { :name => /[\w\.\-\%]+/ }, as: :tree
  get '/:platform/:name/sourcerank', to: 'projects#sourcerank', as: :project_sourcerank, constraints: { :name => /.*/ }

app/controllers/admin/github_repositories_controller.rb
class Admin::GithubRepositoriesController < Admin::ApplicationController
  def show
    @github_repository = GithubRepository.find(params[:id])
  end

  def update
    @github_repository = GithubRepository.find(params[:id])
    if @github_repository.update_attributes(github_repository_params)
      @github_repository.update_all_info_async
      redirect_to github_repository_path(@github_repository.owner_name, @github_repository.project_name)
    else
      redirect_to admin_github_repository_path(@github_repository.id)
    end
  end

  def deprecate
    change(:deprecate!)
  end

  def unmaintain
    change(:unmaintain!)
  end

  def index
    if params[:language].present?
      @language = GithubRepository.language(params[:language].downcase).first.try(:language)
      raise ActiveRecord::RecordNotFound if @language.nil?
      scope = GithubRepository.language(@language)
    else
      scope = GithubRepository
    end

    @languages = GithubRepository.maintained.without_license.with_projects.group('github_repositories.language').count.sort_by(&:last).reverse.first(20)
    @github_repositories = scope.maintained.without_license.with_projects.order("COUNT(projects.id) DESC").group("github_repositories.id").paginate(page: params[:page])
  end

  def deprecated
    search('deprecated')
  end

  def unmaintained
    search('unmaintained')
  end

  private

  def github_repository_params
    params.require(:github_repository).permit(:license, :status)
  end

  def search(query)
    @search = GithubRepository.search(query, must_not: [
      terms: { "status" => ["Unmaintained","Active","Deprecated"] }
    ], sort: 'stargazers_count').paginate(page: params[:page])
    @github_repositories = @search.records
  end

  def change(method)
    @github_repository = GithubRepository.find(params[:id])
    @github_repository.send(method)
    @github_repository.update_all_info_async
    redirect_to github_repository_path(@github_repository.owner_name, @github_repository.project_name)
  end
end

app/controllers/api/github_repositories_controller.rb
class Api::GithubRepositoriesController < Api::ApplicationController
  before_action :find_repo, except: :search

  def show
    render json: @github_repository.as_json({
      except: [:id, :github_organisation_id, :owner_id]
    })
  end

  def projects
    paginate json: project_json_response(@github_repository.projects.includes(:versions, :github_repository))
  end

  def dependencies
    repo_json = @github_repository.as_json({
      except: [:id, :github_organisation_id, :owner_id]
    })
    repo_json[:dependencies] = map_dependencies(@github_repository.repository_dependencies || [])

    render json: repo_json
  end

  def search
    @search = paginate(search_repos(params[:q]))
    ids = @search.map{|r| r.id.to_i }
    indexes = Hash[ids.each_with_index.to_a]
    @github_repositories = @search.records.sort_by { |u| indexes[u.id] }
    render json: @github_repositories.as_json({ except: [:id, :github_organisation_id, :owner_id] })
  end

  private

  def find_repo
    full_name = [params[:owner], params[:name]].join('/')
    @github_repository = GithubRepository.open_source.where('lower(full_name) = ?', full_name.downcase).first

    raise ActiveRecord::RecordNotFound if @github_repository.nil?
  end

  def allowed_sorts
    ['stargazers_count', 'github_contributions_count', 'created_at', 'pushed_at', 'subscribers_count', 'open_issues_count', 'forks_count', 'size']
  end
end

app/views/github_repositories/forks.html.erb
<% title "Repositories forked from #{@github_repository} - Libraries.io" %>

<h1>Repositories forked from <%= link_to @github_repository.full_name, github_repository_path(@github_repository.owner_name, @github_repository.project_name) %></h1>
<hr>
<div class="row">
  <div class="col-sm-8">
    <% if @forks.length > 0 %>
      <%= render @forks, cache: true %>
      <%= will_paginate @forks, page_links: false %>
    <% else %>
      <p>
        No repositories found, go back to <%= link_to @github_repository.full_name, github_repository_path(@github_repository.owner_name, @github_repository.project_name) %>.
      </p>
    <% end %>
  </div>
  <div class="col-sm-4">
    <%= render 'adsense/sidebar' %>
  </div>
</div>

app/views/github_repositories/hacker_news.html.erb
<% title "Trending Repositories - Libraries.io" %>
<h1><i class="fa fa-line-chart"></i> Trending Repositories</h1>

<div class="row">
  <div class="col-sm-8">
    <%= render @repos, cache: true %>
    <%= will_paginate @repos, page_links: false %>
  </div>
  <div class="col-sm-4">
    <%= render 'adsense/sidebar' %>
    <h3>
      <strong>
        How does this work?
      </strong>
    </h3>
    <p>
      This page applies a simplfied version of the <%= link_to 'hacker news algorithm', 'https://news.ycombinator.com/item?id=1781013' %> to open source repositories created within the past 7 days, where stars are used instead of upvotes.
    </p>
    <p>
      It highlights new and interesting projects across all of GitHub, updated in real time using the <%= link_to 'GitHub firehose', 'https://developer.github.com/v3/activity/events/#list-public-events' %>.
    </p>
    <p>
      <%= link_to 'Browse the newest repositories here', new_repos_path %>
    </p>
    <div class='row'>
      <% if @languages.any? %>
        <div class='col-md-12 facets'>
          <h4>Filter by language</h4>
          <ul class='filter'>
            <% @languages.each do |language| %>
              <li class='<%= 'active' if language[0].downcase == params[:language].try(:downcase) %>'>
                <% if language[0].downcase == params[:language].try(:downcase) %>
                  <%= link_to format_language(language[0]), trending_path(language: nil, license: params[:license]) %>
                <% else %>
                  <%= link_to format_language(language[0]), trending_path(language: format_language(language[0]), license: params[:license]) %>
                  <small><%= pluralize number_to_human(language[1]), 'repos' %></small>
                <% end %>
              </li>
            <% end %>
            <% if @language && !@languages.map{|l| l[0].downcase }.include?(@language.name.downcase) %>
              <li class='active'>
                <%= link_to format_language(@language.name), trending_path(language: nil, license: params[:license]) %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/github_repositories/languages.html.erb
<% title "Programming Languages - Libraries.io" %>
<% description "All the programming languages that every repository has been written in." %>
<h1>
  <i class="fa fa-github"></i> Programming Languages
</h1>
<hr>
<div class='row'>
  <% @languages.each do |language| %>
    <div class='language col-xs-6 col-sm-4 col-md-3'>
      <h4>
        <div class="pictogram pictogram-<%= language.term.downcase %>"></div>
        <div class="blurb">
          <%= link_to language.term, github_search_path(language: language.term) %>
          <small><%= number_to_human language['count'] %> Repos</small>
        </div>
      </h4>
    </div>
  <% end %>
</div>

app/views/github_repositories/show.html.erb
<% title "#{@github_repository.full_name} - Libraries.io" %>
<% description @github_repository.description_with_language %>
<%= content_for :meta, render_meta(@github_repository) %>
<% repo = @github_repository %>

<% if !repo.private? && repo.is_removed? %>
<div class="alert alert-danger" role="alert">
  <%= fa_icon 'exclamation-triangle' %>
  This repository has been removed and cannot be used anymore.
</div>
<% elsif !repo.private? && repo.is_deprecated? %>
<div class="alert alert-danger" role="alert">
  <%= fa_icon 'exclamation-triangle' %>
  This repository has been marked as deprecated and is not recommended for use anymore.
</div>
<% elsif !repo.private? && repo.is_unmaintained? %>
<div class="alert alert-danger" role="alert">
  <%= fa_icon 'exclamation-triangle' %>
  This repository has been marked as unmaintained and is no longer being updated.
</div>
<% end %>

<div class="row">
  <div class='col-md-8'>
    <h1>
      <%= link_to image_tag(repo.avatar_url(100), width: 50, height: 50, alt: repo), user_path(repo.owner_name) %>
      <%= repo %>
      <%= link_to fa_icon('github'), repo.url, class: 'tip', title: "View #{repo} on GitHub" %>
      <%= fa_icon("lock", title: 'This repo is private', class: 'tip') if repo.private? %>
      <% if repo.fork? %>
        <% if repo.source.present? || repo.source_name.present? %>
          <%= link_to fa_icon('code-fork'), source_path(repo), class: 'tip', title: "Forked from #{repo.source_name}" %>
        <% else %>
          <%= fa_icon("code-fork", title: 'This repo is a fork', class: 'tip') %>
        <% end %>
      <% end %>
    </h1>
    <% if repo.fork? %>
      <small>
        Forked
        <% if repo.source.present? || repo.source_name.present? %>
          from
          <%= link_to repo.source_name, source_path(repo) %>
        <% end %>
      </small>
    <% end %>
  </div>
  <div class="col-md-4">

    <% if current_user && current_user.can_monitor?(repo) %>
      <br>
        <br>
      <% if sub = current_user.subscribed_to_repo?(repo) %>
        <div class="btn-group pull-right">
          <%= link_to unwatch_path(repo.id), method: :post, class: 'tip btn btn-success', title: 'Stop watching' do %>
            <%= fa_icon('check') %>
            Monitoring
          <% end %>
          <%= link_to fa_icon('cog'), edit_repository_subscription_path(sub), class: 'btn btn-success' %>
        </div>
      <% else %>
        <%= button_to watch_path(repo.id), method: :post, class: 'btn btn-primary btn-default  pull-right tip', title: 'Automatically watch every dependency of this project' do %>
          <%= fa_icon('eye') %>
          Monitor dependencies
        <% end %>
      <% end %>
      <%= link_to github_repository_web_hooks_path(repo.owner_name, repo.project_name), class: 'btn btn-info pull-right', id: 'webhooks' do %>
        <%= fa_icon 'plug' %>
        Web Hooks
      <% end %>
    <% end %>
    <% if logged_in? && current_user.admin? %>
      <%= link_to 'Admin', admin_github_repository_path(repo.id), class: 'btn btn-primary pull-right', rel: 'nofollow' %>
    <% end %>
  </div>
</div>
<hr>
<% cache([@github_repository, 'show', 'v1'], :expires_in => 1.day) do %>
  <div class='row'>
    <div class='col-md-8'>
      <p>
        <%= emojify repo.description %>
      </p>
      <% if repo.homepage.present? %>
        <p>
          <%= link_to repo.homepage, sanitize_url(repo.homepage), :rel => 'nofollow' %>
        </p>
      <% end %>
      <% if repo.license.present? %>
        <p>
          License: <%= link_to format_license(repo.license), license_path(repo.license) %>
        </p>
      <% end %>
      <% if repo.language.present? %>
      <p>
        Language: <%= link_to repo.language, language_path(repo.language) %>
      </p>
      <% end %>
      <% if repo.keywords.any? %>
      <p>
        Keywords: <%= linked_repo_keywords repo.keywords %>
      </p>
      <% end %>
      <% if repo.mirror_url.present? %>
      <p>
        Mirror of <%= repo.mirror_url %>
      </p>
      <% end %>
      <% if repo.readme.present? %>
        <hr>
        <%= render 'adsense/banner' %>
        <%== repo.readme %>
      <% end %>

      <% if @manifests.length > 0 %>
        <hr>
        <div id="dependencies" class="table-responsive">
          <h4>Dependencies</h4>
          <% @manifests.each do |manifest| %>
            <% deps = manifest.repository_dependencies %>
            <% if deps.length > 0 %>
              <table class='table table-hover table-condensed'>
                <thead>
                  <th>
                    <div class="pictogram tip pictogram-<%= manifest.platform.try(:downcase) %>" title='<%= manifest.platform %>'></div>
                    <%= link_to manifest.filepath, manifest.github_link %>
                  </th>
                  <th>Kind</th>
                  <th>
                    Requirements
                  </th>
                  <th>
                    Latest Stable
                  </th>
                  <th>
                    Latest Release
                  </th>
                  <th>
                    Licenses
                  </th>
                  <th>

                  </th>
                </thead>
                <% deps.first(200).reject{|dep| dep.project_name.blank? }.sort_by(&:project_name).each do |dependency| %>
                  <tr>
                    <td>
                      <% if dependency.platform.present? %>
                        <%= link_to  truncate_with_tip(dependency.project_name, 30), project_path(name: dependency.project_name, platform: PackageManager::Base.dependency_platform(dependency.platform)) %>
                      <% else %>
                        <%= truncate_with_tip(dependency.project_name, 30) %>
                      <% end %>
                    </td>
                    <td>
                      <%= truncate_with_tip(dependency.kind, 15) %>
                    </td>
                    <td>
                      <%= truncate_with_tip(dependency.requirements, 15) %>
                    </td>
                    <td>
                      <%= dependency.try(:project).try(:latest_stable_release_number) %>
                    </td>
                    <td>
                      <%= dependency.try(:project).try(:latest_release_number) %>
                    </td>
                    <td>
                      <% if dependency.project %>
                        <%= linked_licenses dependency.project.normalized_licenses %>
                      <% end %>
                    </td>
                    <td>
                      <% if dependency.project %>
                        <%= render 'dependencies/flags', dependency: dependency %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </table>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class='col-md-4'>
      <%= render 'adsense/sidebar' %>
      <h4>Project Statistics</h4>
      <table class='table table-striped'>
        <% if repo.rank %>
        <tr>
          <td>
            Sourcerank
          </td>
          <td>
            <strong><%= link_to repo.rank, github_repository_sourcerank_path(repo.owner_name, repo.project_name) %></strong>
          </td>
        </tr>
        <% end %>
        <tr>
          <td>
            Size
          </td>
          <td>
            <strong><%= number_to_human_size repo.size*1000 %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Stars
          </td>
          <td>
            <strong><%= link_to number_with_delimiter(repo.stargazers_count || 0), repo.stargazers_url %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Forks
          </td>
          <td>
            <strong><%= link_to number_with_delimiter(repo.forks_count || 0), repo.forks_url %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Watchers
          </td>
          <td>
            <strong><%= link_to number_with_delimiter(repo.subscribers_count || 0), repo.watchers_url %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Open issues
          </td>
          <td>
            <strong><%= repo.has_issues? ? link_to(number_with_delimiter(repo.open_issues_count || 0), repo.issues_url) : 'disabled'  %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Dependencies
          </td>
          <td>
            <strong><%= number_with_delimiter repo.repository_dependencies.count %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Contributors
          </td>
          <td>
            <strong><%= link_to number_with_delimiter(repo.contributors.count), github_repository_contributors_path(@github_repository.owner_name, @github_repository.project_name)  %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Tags
          </td>
          <td>
            <strong><%= link_to number_with_delimiter(repo.github_tags.count), github_repository_tags_path(@github_repository.owner_name, @github_repository.project_name)  %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Created
          </td>
          <td>
            <strong><%= timeago_tag repo.created_at %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Last updated
          </td>
          <td>
            <strong><%= timeago_tag repo.updated_at %></strong>
          </td>
        </tr>
        <tr>
          <td>
            Last pushed
          </td>
          <td>
            <strong><%= repo.pushed_at.present? ? timeago_tag(repo.pushed_at) : 'Never'  %></strong>
          </td>
        </tr>
      </table>

      <% if @contributors.length > 0 %>
        <h4>Top Contributors <small><%= link_to 'See all', github_repository_contributors_path(@github_repository.owner_name, @github_repository.project_name) %></small></h4>
        <%= render @contributors %>
      <% end %>

      <% if @projects.length > 0 %>
        <div class="row"></div>
        <hr>
        <h4>Projects Referencing this Repo</h4>
        <%= render @projects, cache: true %>
      <% end %>

      <% if @forks.length > 0 %>
        <div class="row"></div>
        <hr>
        <h4>
          Interesting Forks
          <small><%= link_to 'See all', github_repository_forks_path(@github_repository.owner_name, @github_repository.project_name) %></small>
        </h4>
        <%= render @forks, cache: true %>
      <% end %>

      <% if repo.github_tags.published.length > 0 %>
        <div class="row"></div>
        <hr>
        <h4>
          Tags
          <small><%= link_to 'See all', github_repository_tags_path(@github_repository.owner_name, @github_repository.project_name) %></small>
        </h4>
        <ul>
          <% repo.github_tags.published.order('published_at DESC, name DESC').limit(30).to_a.each do |tag| %>
            <li>
              <%= link_to tag, tag.github_url %>
              <% if tag.published_at.present? %>
              - <%= tag.published_at.to_s(:long) %>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>
      <div class="row"></div>
      <br>
      <p>
        <%= fa_icon 'question-circle' %>
        Something wrong with this page?
        <%= link_to 'Make a suggestion', 'https://github.com/librariesio/support' %>
      </p>
      <% if repo.last_synced_at.present? %>
        <p>
          <small class='text-muted'>Last synced: <%= repo.last_synced_at %></small>
        </p>
      <% end %>
    </div>
  </div>
<% end %>